const express = require('express');
const favicon = require('serve-favicon');
const crossOrigin = require('cors');
const cookieParser = require('cookie-parser');
const appRoot = require('app-root-path');
const bodyParser = require('body-parser');
const helmet = require('helmet');
const env = require('dotenv');
const morganLogger = require('.middleware/morgan.logger');
const defaultController = require('./controllers/default.controller');
const {
  notFoundRoute,
  errorHandler,
} = require('./middleware/error.middleware');
const corsOptions = require('./configs/cors.config');
const authRoute = require('./routes/auth.routes');
const userRoute = require('./routes/user.routes');
const appsRoute = require('./routes/apps.routes');
env.config();
const app = express();
const connectDatabase = require('./database/connect.mongo.db');
connectDatabase();
app.use(morganLogger());
app.use(helmet.crossOriginResourcePolicy({ policy: 'cross-origin' }));
app.use(crossOrigin(corsOptions));
app.use(cookieParser());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
app.use(favicon(`${appRoot}/public/favicon.ico`));
app.use(express.static(`${appRoot}/public`));
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(favicon(`${appRoot}/public/favicon.ico`));
app.use(express.static(`${appRoot}/public`));
app.get('/', defaultController);
app.use('/api/v1', authRoute);
app.use('/api/v1', userRoute);
app.use('/api/v1', appsRoute);
app.use(notFoundRoute);
app.use(errorHandler);
module.exports = app;
